"""add amount column to user_holdings

Revision ID: 6cb84a5411c7
Revises: 734aa0574589
Create Date: 2020-10-22 16:40:40.259950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb84a5411c7'
down_revision = '734aa0574589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_holdings', sa.Column('amount', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_holdings', 'amount')
    # ### end Alembic commands ###
